### ISSUE TITLE
Flipper IR conversion

### ISSUE THREAD

**Issue by Wisiewig** [Spexivus/csv2ir#8]
Hello,

I want to convert EVERY (_converted_) file, into a file that the flipper can use. My discord is Wisiewig#1369, can you add me so we could discuss this?

**Comment by Spexivus** [comment]
Hey,

I'm not entirely sure what you're asking. All the converted files should
run on the flipper, however they may not provide the IR pattern the device
you're testing them on actually wants.

Fixing this isn't feasible since some of the csv files either use
unsupported formats, or require guesswork for setting the subdevice bits
correctly. Even if these formats were supported and you wanted to guess
every subdevice bit, it would be *nearly* impossible to test every single
device in the database, therefore you wouldn't know if the file actually
controls the device properly.

It's been a while since I've touched any of this, but hopefully that makes
sense.
